### ISSUE TITLE
Value should be a JSON object.

### ISSUE THREAD

**Issue by Onoro** [cuimingkun/zbx_tem_redis#5] opened 2019-01-08 09:53 UTC
Hello, cuimingkun.
Thank you for your project! I want to ask for help , I can't get zbx_tem_redis to work.
There is an error appear in Zabbix "Value should be a JSON object.". 
Can you provide me with any advice or debug instruction?

OS and software: Ubuntu 16, Zabbix server 3.4, Redis 4.
What I've done:
I paste content of userparameter_redis_lld_plus.conf to Zabbix configuration file zabbix_agentd.conf and imported template.

![screenshot_2019-01-08](https://user-images.githubusercontent.com/22278106/50819811-ce7bf200-1333-11e9-814f-529943f52182.png)

Attempts to find out where is the problem:
```
root@ubnt-redis-back-replica:/home/pa# zabbix_agentd -t "redis.repl.discovery"
redis.repl.discovery                          [t|sh: 1: [: unexpected operator
sh: 1: [: unexpected operator]

root@ubnt-redis-back-replica:/home/pa# zabbix_agentd -t "redis.port.discovery"
redis.port.discovery                          [t|{"data":[{"{#REDIS_PORT}": "6379"},{"{#REDIS_PORT}": "6379"}]}]

root@ubnt-redis-back-replica:/home/pa# zabbix_agentd -t "redis.port.ping[6379]"
redis.port.ping[6379]                         [t|1]


root@ubnt-redis-back-replica:/home/pa# zabbix_agentd -t "redis.config.json[6379]"
redis.config.json[6379]                       [t|{"redis_config":{"dbfilename":"dump.rdb","requirepass":"","masterauth":"","cluster-announce-ip":"","unixsocket":"","logfile":"/var/log/redis/redis-server.log","pidfile":"/var/run/redis/redis-server.pid","slave-announce-ip":"","maxmemory":"15032385536","proto-max-bulk-len":"536870912","client-query-buffer-limit":"1073741824","maxmemory-samples":"5","lfu-log-factor":"10","lfu-decay-time":"1","timeout":"0","active-defrag-threshold-lower":"10","active-defrag-threshold-upper":"100","active-defrag-ignore-bytes":"104857600","active-defrag-cycle-min":"25","active-defrag-cycle-max":"75","auto-aof-rewrite-percentage":"100","auto-aof-rewrite-min-size":"67108864","hash-max-ziplist-entries":"512","hash-max-ziplist-value":"64","list-max-ziplist-size":"-2","list-compress-depth":"0","set-max-intset-entries":"512","zset-max-ziplist-entries":"128","zset-max-ziplist-value":"64","hll-sparse-max-bytes":"3000","lua-time-limit":"5000","slowlog-log-slower-than":"10000","latency-monitor-threshold":"0","slowlog-max-len":"128","port":"6379","cluster-announce-port":"0","cluster-announce-bus-port":"0","tcp-backlog":"65534","databases":"16","repl-ping-slave-period":"10","repl-timeout":"600","repl-backlog-size":"1048576","repl-backlog-ttl":"3600","maxclients":"100000","watchdog-period":"0","slave-priority":"100","slave-announce-port":"0","min-slaves-to-write":"0","min-slaves-max-lag":"10","hz":"10","cluster-node-timeout":"15000","cluster-migration-barrier":"1","cluster-slave-validity-factor":"10","repl-diskless-sync-delay":"5","tcp-keepalive":"60","cluster-require-full-coverage":"yes","cluster-slave-no-failover":"no","no-appendfsync-on-rewrite":"no","slave-serve-stale-data":"yes","slave-read-only":"yes","stop-writes-on-bgsave-error":"yes","daemonize":"yes","rdbcompression":"yes","rdbchecksum":"yes","activerehashing":"yes","activedefrag":"no","protected-mode":"yes","repl-disable-tcp-nodelay":"no","repl-diskless-sync":"no","aof-rewrite-incremental-fsync":"yes","aof-load-truncated":"yes","aof-use-rdb-preamble":"no","lazyfree-lazy-eviction":"no","lazyfree-lazy-expire":"no","lazyfree-lazy-server-del":"no","slave-lazy-flush":"no","maxmemory-policy":"volatile-lru","loglevel":"notice","supervised":"systemd","appendfsync":"everysec","syslog-facility":"local0","appendonly":"no","dir":"/var/lib/redis","save":"100000","client-output-buffer-limit":"60","unixsocketperm":"0","slaveof":"","notify-keyspace-events":"","bind":"127.0.0.1"}}]

redis.info.json works fine too.

root@ubnt-redis-back-replica:/home/pa# zabbix_agentd -t "redis.slaveinfo.json[6379]"
redis.slaveinfo.json[6379]                    [t|{"redis_slaveinfo":{"role":"master","connected_slaves":"1","slave0":"ip=10.10.0.146,port=6379,state=online,offset=298678926759,lag=1","master_replid":"d4ded430a817bd2336e575ffe88d161210b90fe2","master_replid2":"0000000000000000000000000000000000000000","master_repl_offset":"298683221234","second_repl_offset":"-1","repl_backlog_active":"1","repl_backlog_size":"1048576","repl_backlog_first_byte_offset":"298682172659","repl_backlog_histlen":"1048576"}}]

root@ubnt-redis-back-replica:/home/pa# zabbix_agentd -t "redis.slaveinfo.json[6379,master_last_io_seconds_ago]"
redis.slaveinfo.json[6379,master_last_io_seconds_ago] [t|{"redis_slaveinfo":{"role":"master","connected_slaves":"1","slave0":"ip=10.10.0.146,port=6379,state=online,offset=303343881888,lag=1","master_replid":"d4ded430a817bd2336e575ffe88d161210b90fe2","master_replid2":"0000000000000000000000000000000000000000","master_repl_offset":"303349450787","second_repl_offset":"-1","repl_backlog_active":"1","repl_backlog_size":"1048576","repl_backlog_first_byte_offset":"303348402212","repl_backlog_histlen":"1048576"}}]
```

**Comment by Onoro** [comment] 2019-01-08 14:14
The [nearest topic](https://github.com/cuimingkun/zbx_tem_redis/issues/2 ) helped me to resolve that problem partially, I was forced to add "sudo" to UserParameter string.
Also I specified allowed apps in /etc/sudoers for user zabbix:
`zabbix ALL= (ALL) NOPASSWD: /usr/sbin/smartctl,/etc/zabbix/scripts/smartctl-disks-discovery.pl,/var/lib/zabbix/percona/scripts/get_mysql_stats_wrapper.sh,/usr/bin/telnet,/usr/bin/redis-cli,/bin/sed,/bin/grep,/usr/bin/awk,/bin/bash,/bin/sh,/bin/ss`

"Redis Discovery for Port" rule works fine, but "Redis Discovery for slave Port" rule status still "Value should be a JSON object." As far as I understood, problem is here:

root@ubnt-redis-back-replica:/home/pa# zabbix_agentd -t "redis.repl.discovery"
redis.repl.discovery                          [t|sh: 1: [: slave: unexpected operator
sh: 1: [: slave: unexpected operator]
 
root@ubnt-redis-back-replica:/home/pa# zabbix_agentd -t "redis.repl.discovery"
redis.repl.discovery                          [t|sh: 1: [: unexpected operator
sh: 1: [: unexpected operator]

**Comment by subcreat0r** [comment] 2019-01-09 18:57
Same error for me - Value should be a JSON object.
It seems zabbix user on a monitored host should have root privileges to list sockets with ss command

With root its ok
```
# ss -4lp|grep redis-server|awk -F':' '{print $2}'|awk '{print $1}'| awk NF | sed -e s/^/'{"{#REDIS_PORT}": "'/g -e s/'$'/'"},'/g | tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}/g
{"data":[{"{#REDIS_PORT}": "6379"}]}

```

With zabbix user I get empty string
`$ ss -4lp|grep redis-server|awk -F':' '{print $2}'|awk '{print $1}'| awk NF | sed -e s/^/'{"{#REDIS_PORT}": "'/g -e s/'$'/'"},'/g | tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}/g
`

I found a simple solution - change 2 lines in userparameter_redis_lld_plus.conf

```
UserParameter=redis.port.discovery,awk -F: '{print $2}' /proc/`pidof redis-server`/cmdline | sed -e s/^/'{"{#REDIS_PORT}": "'/g -e s/'$'/'"},'/g | tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}/g

UserParameter=redis.repl.discovery,awk -F: '{print $2}' /proc/`pidof redis-server`/cmdline | while read line; do role=`(echo info ; sleep 0.1)|telnet 127.0.0.1 $line 2>/dev/null|grep 'role:slave'|awk -F ':' '{print $2}'`;if [ "$role" == "slave" ] ;then echo "SLAVE:$line"|sed -e s/^/'{"{#REDIS_PORT_'/g -e s/'$'/'"},'/g -e s/':'/'}": "'/g ; fi;done| tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}/g

```

P.S. And it also doesn't work ;)
Some issue with sed commands...
I got truncated output
```
# zabbix_get -s domain.com -k 'redis.port.discovery'
{"data":[{"{#REDIS_PORT}": "6379
```

And finally it WORKS fine with this.

```
UserParameter=redis.port.discovery,echo -n '{"data":[{"{#REDIS_PORT}": "'; awk -F: '{print $2}' /proc/`pidof redis-server`/cmdline | tr -d \\n; echo -n '"}]}'
```

**Comment by cuimingkun** [comment] 2019-01-22 03:07
Sorry, I haven't responded for a long time.
Because of the use of "ss" command, so , Should have root privileges to list sockets with ss command.
Forget to remind, my apologetic.

@Onoro 
The problems you encounter，It may be related to the system environment or command usage.
You can step by step execute the command manually to check it. Find the wrong spot. Simple modifications should be required.

@subcreat0r 
Thank you very much for your suggestion.
But if there are more than one "redis-server" process. Maybe there will be problems.

**Comment by manjeetlakra** [comment] 2019-03-12 10:43
4516:20190312:161106.211 error reason for "Redis Server:redis.info.json[6379,rdb_bgsave_in_progress]" changed: Item preprocessing step #1 failed: cannot extract value from json by path "$.redis_info.rdb_bgsave_in_progress":
  4516:20190312:161106.211 error reason for "Redis Server:redis.info.json[6379,aof_last_rewrite_time_sec]" changed: Item preprocessing step #1 failed: cannot extract value from json by path "$.redis_info.aof_last_rewrite_time_sec":
  4516:20190312:161106.211 error reason for "Redis Server:redis.info.json[6379,aof_rewrite_in_progress]" changed: Item preprocessing step #1 failed: cannot extract value from json by path "$.redis_info.aof_rewrite_in_progress": object not found starting with json path: "maxmemory"
  4516:20190312:161106.211 error reason for "Redis Server:redis.info.json[6379,rdb_last_bgsave_status]" changed: Item preprocessing step #1 failed: cannot extract value from json by path "$.redis_info.rdb_last_bgsave_status":

Getting above errors in zabbix server logs. Can you help me resolve it ?

**Comment by cuimingkun** [comment] 2019-03-13 07:01
You can  execute command corresponding to "redis.info.json" ,check it.

**Comment by manjeetlakra** [comment] 2019-03-13 07:30
no data is coming
zabbix_agentd -t "redis.info.json[6379,maxclients]"
redis.info.json[6379,maxclients]              [t|]

**Comment by manjeetlakra** [comment] 2019-03-13 11:30
At agent now I am getting values but at zabbix server same error

4516:20190312:161106.211 error reason for "Redis Server:redis.info.json[6379,rdb_last_bgsave_status]" changed: Item preprocessing step #1 failed: cannot extract value from json by path "$.redis_info.rdb_last_bgsave_status":

**Comment by OrangeDog** [comment] 2019-05-29 09:54
This is a duplicate of #2, which is now fixed.

**Closed as completed** 2019-08-21 10:00 UTC
